NumPyのImport

以下のNumPyのセクションを参照のこと。通常、NumPyなどのパッケージはコードの最初でimportされる

In [7]:
import numpy as np

## コンテナ型

### リスト

リストの作成

リストの中身は数値や文字列でもなんでも良い

In [29]:
x = [1, 2, 3]
y = ["Hello", " ", "world"]

リストのi番目の要素を取り出すときは[i]で指定する(Pythonは0始点)

In [30]:
print(x[0], y[2])

1 world


リストに対する演算や操作

In [31]:
x + y # リスト x と y を結合

[1, 2, 3, 'Hello', ' ', 'world']

In [32]:
len(x) # リスト x の長さを取得

3

In [33]:
2 in x # x が 2 という要素を含むか否か

True

In [183]:
x[0] = "A" # x の0番目の要素を "A" に置き換える
x.append("X") # x の最後に "X" を追加（メソッド）
for a in x: # x の要素で繰り返し処理。
    print("a=", a) # この場合 a= A (改行) a= 2　(改行) a= 3　(改行) a= X と連続して出力

a= A
a= 2
a= 3
a= X
a= X


### タプル

タプルの作成：

カンマで要素を区切ることで定義される

In [38]:
t = 1,2,3
t = (1,2,3) # 丸括弧()で囲んでも良い

一度作成されたタプルは修正できない（以下の操作はエラーを吐く）：

In [39]:
t[0] = "A"

TypeError: 'tuple' object does not support item assignment

このように、タプル t を再定義することは可能：

In [40]:
t = "A",2,3

タプルの便利な使い方

In [41]:
a, b = 1, 2  #複数の変数の初期化
b, a = a, b  #変数の値の交換

### 集合

集合の作成：

波括弧で囲むか、リストをset()に渡すことでも定義できる

In [42]:
s1 = {1,2,3,3,4}
s2 = set([3,1,5,5,5,4])

In [43]:
print(s1, s2) # 重複部分は取り除かれる

{1, 2, 3, 4} {1, 3, 4, 5}


In [44]:
print("s1 =",s1,",  s2 =",s2)
print("s1 | s2 =", s1 | s2, " ←s1とs2の和集合")
print("s1 & s2 =", s1 & s2, "       ←s1とs2の共通部分") 
print("s1 ^ s2 =", s1 ^ s2, "          ←s1とs2の対称差")

s1 = {1, 2, 3, 4} ,  s2 = {1, 3, 4, 5}
s1 | s2 = {1, 2, 3, 4, 5}  ←s1とs2の和集合
s1 & s2 = {1, 3, 4}        ←s1とs2の共通部分
s1 ^ s2 = {2, 5}           ←s1とs2の対称差


### 辞書型

キー（Key）と値（Value）の組を保持する型

コードの可読性を向上させるので、データ処理のよく用いられる

In [46]:
# 辞書型：{"key1":value1, ...} のように書く
teisuu = {"hbar":1.055e-34, "c":1.0}

In [50]:
print(teisuu["hbar"]) # Key="hbar"のValueを取得
teisuu["c"] = 2.998e+8 # Key="c"のValueを変更
teisuu["e"] = 1.602e-19 # {"e":1.602e-19}の要素を追加

1.055e-34


In [51]:
for key, value in teisuu.items():
    # teisuuに適用された.itemsというメソッドは
    # keyとvalueの組を取得。反復処理に用いる
    print(key, value)

hbar 1.055e-34
c 299800000.0
e 1.602e-19


# NumPy

### 配列の作成

In [23]:
a = np.array([1,2,3])
b = np.array([[1,2,3],[4,5,6]]) # 2次元配列（行列）や、より高次元のd次元配列も作成できる

その他有用な配列の作成

In [25]:
np.zeros(2) # 要素が全て0で、長さが2の1次元配列

array([0., 0.])

In [26]:
np.ones((2,2)) # 要素が全て1で、大きさが 2x2 の2次元配列

array([[1., 1.],
       [1., 1.]])

In [52]:
np.arange(2,9,2) # 2以上9未満で2刻み（この場合偶数）の配列

array([2, 4, 6, 8])

In [53]:
np.linspace(0, 10, 5) # 0以上10以下で要素が5個の配列を作成

array([ 0. ,  2.5,  5. ,  7.5, 10. ])

In [54]:
np.eye(10) # 10 x 10 の単位行列

array([[1., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 1., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 1., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 1.]])

型の指定

ndarrayはリストと違って型が固定されている。

In [56]:
a = np.ones(3, dtype=int) # dtypeで要素の型を指定できる。ほとんどの場合デフォルトはfloat
a[1] = 2.2 # a の要素は全て int 型なので小数点以下は切り捨てられる
a

array([1, 2, 1])

### 配列に対する便利な操作

以下、次の配列 a と b に関する操作をいくつか紹介する

In [97]:
a = np.array([2, 1, 5, 3, 7, 4, 6, 8])
b = np.array([9, 10, 11, 12, 13, 14, 15, 16])

データのソート（並び替え）

In [98]:
a = np.sort(a) # a をソートして a に代入する。
a

array([1, 2, 3, 4, 5, 6, 7, 8])

In [99]:
a = np.array([2, 1, 5, 3, 7, 4, 6, 8])
a.sort() # あるいは、このようにメソッドを用いて書くと、ソートをした上で a が上書きされる。なので、代入する必要がない。
a

array([1, 2, 3, 4, 5, 6, 7, 8])

スライス

a[始点 : 終点+1 : n] と書く。a[-1]はaの最後の要素になる。

nは配列をn個おきに取り出すときのnで、n=が負だと逆順のn個おきになる。

In [100]:
a[:3] # 0から2番目までの要素を取り出す。他には、a[2:3], a[-1], a[::2], a[::-1]などという使い方がある。試してみよう。

array([1, 2, 3])

2つの配列の結合

In [101]:
d = np.append(a, b)
d

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16])

配列の形状を任意に変換

In [104]:
e = a.reshape(2, 4) # a を 2 x 4 に変更
e

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

多次元配列を1次元配列に変換

In [105]:
f = e.flatten()
f

array([1, 2, 3, 4, 5, 6, 7, 8])

配列の形状をタプルで取得

In [106]:
g = f.shape 
g

(8,)

配列内の値が0以外の要素のインデックスの取得

Python では bool 型の値 False は0と見做される。

In [149]:
np.nonzero(a==2)[0] # a==2 を満たすインデックスを取得

array([1])

条件を満たす要素のインデックスの取得

np.where(条件) -> 条件を満たすindexの取得

np.where(条件, 値1, 値2) -> 配列中で条件を満たす要素があるときには値1を、それ以外の要素を値2で置き換える

In [121]:
i = np.where(a==2)
j = np.where(a==2, 4, 0)
i, j

((array([1]),), array([0, 4, 0, 0, 0, 0, 0, 0]))

コロン:の用法

In [148]:
e[:, 0] #2次元配列の0列目を取り出す。

array([1, 5])

int 型の配列によるインデックス指定

In [123]:
b[k] # int 型の配列はインデックス指定にも使える

array([10, 14])

配列中で条件を満たす要素への代入

In [127]:
d[d < 3] = 0
d

array([ 0,  0,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16])

### 配列に対する便利な演算

全ての要素への加減乗除べき乗

In [156]:
l = 2.0 * a #掛け算。同様に足し算引き算、べき乗もできる。
l

array([ 2.,  4.,  6.,  8., 10., 12., 14., 16.])

ちなみに、ndarrayではなく、Pythonのリストの場合、この演算はできない。

In [138]:
m = [1, 2, 3, 4, 5, 6, 7, 8]
2.0 * m

TypeError: can't multiply sequence by non-int of type 'float'

Python のリストに int n を掛け算した場合はリストが n 回繰り返される。

In [137]:
2 * m

[1, 2, 3, 4, 5, 6, 7, 8, 1, 2, 3, 4, 5, 6, 7, 8]

配列の要素ごとの加減乗除

同じ形状の配列同士の加減乗除は要素ごとになる

In [146]:
a * b

array([  9,  20,  33,  48,  65,  84, 105, 128])

ベクトルの内積

In [141]:
np.dot(a, b)

492

スライスの応用

In [157]:
o = a[None,:] * b[:,None] # o_ij = a_i * b_j
o

array([[  9,  18,  27,  36,  45,  54,  63,  72],
       [ 10,  20,  30,  40,  50,  60,  70,  80],
       [ 11,  22,  33,  44,  55,  66,  77,  88],
       [ 12,  24,  36,  48,  60,  72,  84,  96],
       [ 13,  26,  39,  52,  65,  78,  91, 104],
       [ 14,  28,  42,  56,  70,  84,  98, 112],
       [ 15,  30,  45,  60,  75,  90, 105, 120],
       [ 16,  32,  48,  64,  80,  96, 112, 128]])

多くのNumPy関数の引数には配列を直接渡すことができる。例えば、
$\cos(2\pi p / 9), \ (p=0, \ldots, 8)$
を求めたい場合は以下のように書くと早い。

In [158]:
p = np.arange(9)
np.cos(2 * np.pi * p / 9)

array([ 1.        ,  0.76604444,  0.17364818, -0.5       , -0.93969262,
       -0.93969262, -0.5       ,  0.17364818,  0.76604444])

### 行列に対する便利な演算、線形代数

In [162]:
A = np.array([[1,1],[0,1]])
B = np.array([[2,0],[3,4]])
C = A * B # 行列要素ごとの積
D = A @ B # 行列としての積
E = A.T #転置
C, D, E

(array([[2, 0],
        [0, 4]]),
 array([[5, 4],
        [3, 4]]),
 array([[1, 0],
        [1, 1]]))

In [170]:
A = np.array([[1,2,3],[2,1,1],[3,2,1]])
F = np.linalg.det(A) # 行列式の計算
G = np.linalg.inv(A) # 逆行列の計算
e, v = np.linalg.eigh(A) # エルミート行列の対角化
print("F=", F)
print("G=", G)
print("Eigenvalues=", e)
print("Eigenvectors=", v)

F= 4.0
G= [[-0.25  1.   -0.25]
 [ 0.25 -2.    1.25]
 [ 0.25  1.   -0.75]]
Eigenvalues= [-2.         -0.70156212  5.70156212]
Eigenvectors= [[-7.07106781e-01  3.64512933e-01 -6.05912800e-01]
 [ 2.22044605e-16 -8.56890100e-01 -5.15499134e-01]
 [ 7.07106781e-01  3.64512933e-01 -6.05912800e-01]]


### アインシュタインの縮約記号

以下は、アインシュタインの縮約記号を行列 (or 2x2のテンソル) $a_{ij}$について適用する。
$$
% \begin{align}
% b= a
% \end{align}
c = a_{ii} := \sum_{i} a_{ii}\\
d_{ik} = a_{ij} b_{jk} := \sum_{j} a_{ij} b_{jk} \\
e_{j} = a_{ii} b_{ij} := \sum_{i} a_{ii} b_{ij}\\
f = a_{ij} b_{kj} a_{ki} := \sum_{i,j,k} a_{ij} b_{kj} a_{ki}
$$

In [ ]:
a = np.random.randn(5,5) # 5 x 5 の乱数行列
b = np.random.randn(5,5) # 5 x 5 の乱数行列
c = np.einsum("ii", a)
d = np.einsum("ij,jk->ik", a, b)
e = np.einsum("ii,ij->j", a, b)
f = np.einsum("ij,kj,ki", a, b, a)

# その他、IPython Notebookの便利な機能

ヘルプ参照

ライブラリの関数の後に?と打てば、そのdocumentationが見られる。

In [173]:
np.linspace?

Signature:      
np.linspace(
    start,
    stop,
    num=50,
    endpoint=True,
    retstep=False,
    dtype=None,
    axis=0,
)
Call signature:  np.linspace(*args, **kwargs)
Type:            _ArrayFunctionDispatcher
String form:     <function linspace at 0x1111d2480>
File:            ~/.pyenv/versions/anaconda3-2024.10-1/lib/python3.12/site-packages/numpy/core/function_base.py
Docstring:      
Return evenly spaced numbers over a specified interval.

Returns `num` evenly spaced samples, calculated over the
interval [`start`, `stop`].

The endpoint of the interval can optionally be excluded.

.. versionchanged:: 1.16.0
    Non-scalar `start` and `stop` are now supported.

.. versionchanged:: 1.20.0
    Values are rounded towards ``-inf`` instead of ``0`` when an
    integer ``dtype`` is specified. The old behavior can
    still be obtained with ``np.linspace(start, stop, num).astype(int)``

Parameters
----------
start : array_like
    The starting value of the sequence.
stop : array_l

時間計測

%%timeitとセルの1行目に書くことで、繰り返しセルを実行し、実行時間を計測する。%%timeは1回限りの実行時間。

In [175]:
%%timeit
k = 1
for i in range(10000):
    k *= i

287 μs ± 33.8 μs per loop (mean ± std. dev. of 7 runs, 1,000 loops each)
